LIMIT_IMAGES = 69445 #number of image to download, 69445 is the max

LIMIT_IMAGES_SEGMENTATION_DOWNLOAD = 5000
LIMIT_IMAGES_SEGMENTATION_PKL = 3500
TEST_SET_SIZE_SEGMENTATION = 200
IMG_CHANNELS_UNET = 1
IMG_SIZE_UNET = 256
EPOCHS_UNET = 30
LR_UNET = 0.0005
BS_UNET = 32
FUNCTION_UNET = 'relu'

LIMIT_IMAGES_CLASSIFICATION_PKL = 10
TEST_SET_SIZE_CLASSIFICATION = 2
IMG_CHANNELS_VGG = 1
IMG_SIZE_VGG = 224
EPOCHS_VGG = 1
LR_VGG = 0.0005
BS_VGG = 32
FUNCTION_VGG = 'relu'

DOWNLOAD_DATASET = False

